version: "3"
services:
  tellform:
    build: 
      context: ./
      dockerfile: dockerfile
    image: tellform
    ports:
      - 3000:3000
    links:
      - tellform-redis:redis-db
      - tellform-mongo:db
    env_file:
      - .env
  tellform-redis:
    image: redis
    ports:
      - 6379
  tellform-mongo:
    image: mongo
    ports:
      - 27017
