
version: '2'
services:
  db:
    image: mongo:3.2
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      DB_1_PORT_27017_TCP_ADDR: db
      PORT: 3000
    links:
      - db
volumes:
  mongo-data-wt:
    driver: local
